result(xray(zero_quad), gipox(very_high), compliance(very_high), pressure(very_low), small).
result(xray(zero_quad), gipox(very_high), compliance(very_high), pressure(low), small).
result(xray(zero_quad), gipox(very_high), compliance(very_high), pressure(mid), small).
result(xray(zero_quad), gipox(very_high), compliance(very_high), pressure(high), small).
result(xray(zero_quad), gipox(very_high), compliance(very_high), pressure(very_high), medium).
result(xray(zero_quad), gipox(very_high), compliance(high), pressure(very_low), small).
result(xray(zero_quad), gipox(very_high), compliance(high), pressure(low), small).
result(xray(zero_quad), gipox(very_high), compliance(high), pressure(mid), small).
result(xray(zero_quad), gipox(very_high), compliance(high), pressure(high), medium).
result(xray(zero_quad), gipox(very_high), compliance(high), pressure(very_high), medium).
result(xray(zero_quad), gipox(very_high), compliance(mid), pressure(very_low), small).
result(xray(zero_quad), gipox(very_high), compliance(mid), pressure(low), small).
result(xray(zero_quad), gipox(very_high), compliance(mid), pressure(mid), medium).
result(xray(zero_quad), gipox(very_high), compliance(mid), pressure(high), medium).
result(xray(zero_quad), gipox(very_high), compliance(mid), pressure(very_high), medium).
result(xray(zero_quad), gipox(very_high), compliance(low), pressure(very_low), small).
result(xray(zero_quad), gipox(very_high), compliance(low), pressure(low), medium).
result(xray(zero_quad), gipox(very_high), compliance(low), pressure(mid), medium).
result(xray(zero_quad), gipox(very_high), compliance(low), pressure(high), medium).
result(xray(zero_quad), gipox(very_high), compliance(low), pressure(very_high), medium).
result(xray(zero_quad), gipox(very_high), compliance(very_low), pressure(very_low), medium).
result(xray(zero_quad), gipox(very_high), compliance(very_low), pressure(low), medium).
result(xray(zero_quad), gipox(very_high), compliance(very_low), pressure(mid), medium).
result(xray(zero_quad), gipox(very_high), compliance(very_low), pressure(high), medium).
result(xray(zero_quad), gipox(very_high), compliance(very_low), pressure(very_high), medium).
result(xray(zero_quad), gipox(high), compliance(very_high), pressure(very_low), small).
result(xray(zero_quad), gipox(high), compliance(very_high), pressure(low), small).
result(xray(zero_quad), gipox(high), compliance(very_high), pressure(mid), small).
result(xray(zero_quad), gipox(high), compliance(very_high), pressure(high), medium).
result(xray(zero_quad), gipox(high), compliance(very_high), pressure(very_high), medium).
result(xray(zero_quad), gipox(high), compliance(high), pressure(very_low), small).
result(xray(zero_quad), gipox(high), compliance(high), pressure(low), small).
result(xray(zero_quad), gipox(high), compliance(high), pressure(mid), medium).
result(xray(zero_quad), gipox(high), compliance(high), pressure(high), medium).
result(xray(zero_quad), gipox(high), compliance(high), pressure(very_high), medium).
result(xray(zero_quad), gipox(high), compliance(mid), pressure(very_low), small).
result(xray(zero_quad), gipox(high), compliance(mid), pressure(low), medium).
result(xray(zero_quad), gipox(high), compliance(mid), pressure(mid), medium).
result(xray(zero_quad), gipox(high), compliance(mid), pressure(high), medium).
result(xray(zero_quad), gipox(high), compliance(mid), pressure(very_high), medium).
result(xray(zero_quad), gipox(high), compliance(low), pressure(very_low), medium).
result(xray(zero_quad), gipox(high), compliance(low), pressure(low), medium).
result(xray(zero_quad), gipox(high), compliance(low), pressure(mid), medium).
result(xray(zero_quad), gipox(high), compliance(low), pressure(high), medium).
result(xray(zero_quad), gipox(high), compliance(low), pressure(very_high), medium).
result(xray(zero_quad), gipox(high), compliance(very_low), pressure(very_low), medium).
result(xray(zero_quad), gipox(high), compliance(very_low), pressure(low), medium).
result(xray(zero_quad), gipox(high), compliance(very_low), pressure(mid), medium).
result(xray(zero_quad), gipox(high), compliance(very_low), pressure(high), medium).
result(xray(zero_quad), gipox(high), compliance(very_low), pressure(very_high), medium).
result(xray(zero_quad), gipox(mid), compliance(very_high), pressure(very_low), small).
result(xray(zero_quad), gipox(mid), compliance(very_high), pressure(low), small).
result(xray(zero_quad), gipox(mid), compliance(very_high), pressure(mid), medium).
result(xray(zero_quad), gipox(mid), compliance(very_high), pressure(high), medium).
result(xray(zero_quad), gipox(mid), compliance(very_high), pressure(very_high), medium).
result(xray(zero_quad), gipox(mid), compliance(high), pressure(very_low), small).
result(xray(zero_quad), gipox(mid), compliance(high), pressure(low), medium).
result(xray(zero_quad), gipox(mid), compliance(high), pressure(mid), medium).
result(xray(zero_quad), gipox(mid), compliance(high), pressure(high), medium).
result(xray(zero_quad), gipox(mid), compliance(high), pressure(very_high), medium).
result(xray(zero_quad), gipox(mid), compliance(mid), pressure(very_low), medium).
result(xray(zero_quad), gipox(mid), compliance(mid), pressure(low), medium).
result(xray(zero_quad), gipox(mid), compliance(mid), pressure(mid), medium).
result(xray(zero_quad), gipox(mid), compliance(mid), pressure(high), medium).
result(xray(zero_quad), gipox(mid), compliance(mid), pressure(very_high), medium).
result(xray(zero_quad), gipox(mid), compliance(low), pressure(very_low), medium).
result(xray(zero_quad), gipox(mid), compliance(low), pressure(low), medium).
result(xray(zero_quad), gipox(mid), compliance(low), pressure(mid), medium).
result(xray(zero_quad), gipox(mid), compliance(low), pressure(high), medium).
result(xray(zero_quad), gipox(mid), compliance(low), pressure(very_high), medium).
result(xray(zero_quad), gipox(mid), compliance(very_low), pressure(very_low), medium).
result(xray(zero_quad), gipox(mid), compliance(very_low), pressure(low), medium).
result(xray(zero_quad), gipox(mid), compliance(very_low), pressure(mid), medium).
result(xray(zero_quad), gipox(mid), compliance(very_low), pressure(high), medium).
result(xray(zero_quad), gipox(mid), compliance(very_low), pressure(very_high), severe).
result(xray(zero_quad), gipox(low), compliance(very_high), pressure(very_low), small).
result(xray(zero_quad), gipox(low), compliance(very_high), pressure(low), medium).
result(xray(zero_quad), gipox(low), compliance(very_high), pressure(mid), medium).
result(xray(zero_quad), gipox(low), compliance(very_high), pressure(high), medium).
result(xray(zero_quad), gipox(low), compliance(very_high), pressure(very_high), medium).
result(xray(zero_quad), gipox(low), compliance(high), pressure(very_low), medium).
result(xray(zero_quad), gipox(low), compliance(high), pressure(low), medium).
result(xray(zero_quad), gipox(low), compliance(high), pressure(mid), medium).
result(xray(zero_quad), gipox(low), compliance(high), pressure(high), medium).
result(xray(zero_quad), gipox(low), compliance(high), pressure(very_high), medium).
result(xray(zero_quad), gipox(low), compliance(mid), pressure(very_low), medium).
result(xray(zero_quad), gipox(low), compliance(mid), pressure(low), medium).
result(xray(zero_quad), gipox(low), compliance(mid), pressure(mid), medium).
result(xray(zero_quad), gipox(low), compliance(mid), pressure(high), medium).
result(xray(zero_quad), gipox(low), compliance(mid), pressure(very_high), medium).
result(xray(zero_quad), gipox(low), compliance(low), pressure(very_low), medium).
result(xray(zero_quad), gipox(low), compliance(low), pressure(low), medium).
result(xray(zero_quad), gipox(low), compliance(low), pressure(mid), medium).
result(xray(zero_quad), gipox(low), compliance(low), pressure(high), medium).
result(xray(zero_quad), gipox(low), compliance(low), pressure(very_high), severe).
result(xray(zero_quad), gipox(low), compliance(very_low), pressure(very_low), medium).
result(xray(zero_quad), gipox(low), compliance(very_low), pressure(low), medium).
result(xray(zero_quad), gipox(low), compliance(very_low), pressure(mid), medium).
result(xray(zero_quad), gipox(low), compliance(very_low), pressure(high), severe).
result(xray(zero_quad), gipox(low), compliance(very_low), pressure(very_high), severe).
result(xray(zero_quad), gipox(very_low), compliance(very_high), pressure(very_low), medium).
result(xray(zero_quad), gipox(very_low), compliance(very_high), pressure(low), medium).
result(xray(zero_quad), gipox(very_low), compliance(very_high), pressure(mid), medium).
result(xray(zero_quad), gipox(very_low), compliance(very_high), pressure(high), medium).
result(xray(zero_quad), gipox(very_low), compliance(very_high), pressure(very_high), medium).
result(xray(zero_quad), gipox(very_low), compliance(high), pressure(very_low), medium).
result(xray(zero_quad), gipox(very_low), compliance(high), pressure(low), medium).
result(xray(zero_quad), gipox(very_low), compliance(high), pressure(mid), medium).
result(xray(zero_quad), gipox(very_low), compliance(high), pressure(high), medium).
result(xray(zero_quad), gipox(very_low), compliance(high), pressure(very_high), medium).
result(xray(zero_quad), gipox(very_low), compliance(mid), pressure(very_low), medium).
result(xray(zero_quad), gipox(very_low), compliance(mid), pressure(low), medium).
result(xray(zero_quad), gipox(very_low), compliance(mid), pressure(mid), medium).
result(xray(zero_quad), gipox(very_low), compliance(mid), pressure(high), medium).
result(xray(zero_quad), gipox(very_low), compliance(mid), pressure(very_high), severe).
result(xray(zero_quad), gipox(very_low), compliance(low), pressure(very_low), medium).
result(xray(zero_quad), gipox(very_low), compliance(low), pressure(low), medium).
result(xray(zero_quad), gipox(very_low), compliance(low), pressure(mid), medium).
result(xray(zero_quad), gipox(very_low), compliance(low), pressure(high), severe).
result(xray(zero_quad), gipox(very_low), compliance(low), pressure(very_high), severe).
result(xray(zero_quad), gipox(very_low), compliance(very_low), pressure(very_low), medium).
result(xray(zero_quad), gipox(very_low), compliance(very_low), pressure(low), medium).
result(xray(zero_quad), gipox(very_low), compliance(very_low), pressure(mid), severe).
result(xray(zero_quad), gipox(very_low), compliance(very_low), pressure(high), severe).
result(xray(zero_quad), gipox(very_low), compliance(very_low), pressure(very_high), severe).
result(xray(one_quad), gipox(very_high), compliance(very_high), pressure(very_low), small).
result(xray(one_quad), gipox(very_high), compliance(very_high), pressure(low), small).
result(xray(one_quad), gipox(very_high), compliance(very_high), pressure(mid), small).
result(xray(one_quad), gipox(very_high), compliance(very_high), pressure(high), medium).
result(xray(one_quad), gipox(very_high), compliance(very_high), pressure(very_high), medium).
result(xray(one_quad), gipox(very_high), compliance(high), pressure(very_low), small).
result(xray(one_quad), gipox(very_high), compliance(high), pressure(low), small).
result(xray(one_quad), gipox(very_high), compliance(high), pressure(mid), medium).
result(xray(one_quad), gipox(very_high), compliance(high), pressure(high), medium).
result(xray(one_quad), gipox(very_high), compliance(high), pressure(very_high), medium).
result(xray(one_quad), gipox(very_high), compliance(mid), pressure(very_low), small).
result(xray(one_quad), gipox(very_high), compliance(mid), pressure(low), medium).
result(xray(one_quad), gipox(very_high), compliance(mid), pressure(mid), medium).
result(xray(one_quad), gipox(very_high), compliance(mid), pressure(high), medium).
result(xray(one_quad), gipox(very_high), compliance(mid), pressure(very_high), medium).
result(xray(one_quad), gipox(very_high), compliance(low), pressure(very_low), medium).
result(xray(one_quad), gipox(very_high), compliance(low), pressure(low), medium).
result(xray(one_quad), gipox(very_high), compliance(low), pressure(mid), medium).
result(xray(one_quad), gipox(very_high), compliance(low), pressure(high), medium).
result(xray(one_quad), gipox(very_high), compliance(low), pressure(very_high), medium).
result(xray(one_quad), gipox(very_high), compliance(very_low), pressure(very_low), medium).
result(xray(one_quad), gipox(very_high), compliance(very_low), pressure(low), medium).
result(xray(one_quad), gipox(very_high), compliance(very_low), pressure(mid), medium).
result(xray(one_quad), gipox(very_high), compliance(very_low), pressure(high), medium).
result(xray(one_quad), gipox(very_high), compliance(very_low), pressure(very_high), medium).
result(xray(one_quad), gipox(high), compliance(very_high), pressure(very_low), small).
result(xray(one_quad), gipox(high), compliance(very_high), pressure(low), small).
result(xray(one_quad), gipox(high), compliance(very_high), pressure(mid), medium).
result(xray(one_quad), gipox(high), compliance(very_high), pressure(high), medium).
result(xray(one_quad), gipox(high), compliance(very_high), pressure(very_high), medium).
result(xray(one_quad), gipox(high), compliance(high), pressure(very_low), small).
result(xray(one_quad), gipox(high), compliance(high), pressure(low), medium).
result(xray(one_quad), gipox(high), compliance(high), pressure(mid), medium).
result(xray(one_quad), gipox(high), compliance(high), pressure(high), medium).
result(xray(one_quad), gipox(high), compliance(high), pressure(very_high), medium).
result(xray(one_quad), gipox(high), compliance(mid), pressure(very_low), medium).
result(xray(one_quad), gipox(high), compliance(mid), pressure(low), medium).
result(xray(one_quad), gipox(high), compliance(mid), pressure(mid), medium).
result(xray(one_quad), gipox(high), compliance(mid), pressure(high), medium).
result(xray(one_quad), gipox(high), compliance(mid), pressure(very_high), medium).
result(xray(one_quad), gipox(high), compliance(low), pressure(very_low), medium).
result(xray(one_quad), gipox(high), compliance(low), pressure(low), medium).
result(xray(one_quad), gipox(high), compliance(low), pressure(mid), medium).
result(xray(one_quad), gipox(high), compliance(low), pressure(high), medium).
result(xray(one_quad), gipox(high), compliance(low), pressure(very_high), medium).
result(xray(one_quad), gipox(high), compliance(very_low), pressure(very_low), medium).
result(xray(one_quad), gipox(high), compliance(very_low), pressure(low), medium).
result(xray(one_quad), gipox(high), compliance(very_low), pressure(mid), medium).
result(xray(one_quad), gipox(high), compliance(very_low), pressure(high), medium).
result(xray(one_quad), gipox(high), compliance(very_low), pressure(very_high), severe).
result(xray(one_quad), gipox(mid), compliance(very_high), pressure(very_low), small).
result(xray(one_quad), gipox(mid), compliance(very_high), pressure(low), medium).
result(xray(one_quad), gipox(mid), compliance(very_high), pressure(mid), medium).
result(xray(one_quad), gipox(mid), compliance(very_high), pressure(high), medium).
result(xray(one_quad), gipox(mid), compliance(very_high), pressure(very_high), medium).
result(xray(one_quad), gipox(mid), compliance(high), pressure(very_low), medium).
result(xray(one_quad), gipox(mid), compliance(high), pressure(low), medium).
result(xray(one_quad), gipox(mid), compliance(high), pressure(mid), medium).
result(xray(one_quad), gipox(mid), compliance(high), pressure(high), medium).
result(xray(one_quad), gipox(mid), compliance(high), pressure(very_high), medium).
result(xray(one_quad), gipox(mid), compliance(mid), pressure(very_low), medium).
result(xray(one_quad), gipox(mid), compliance(mid), pressure(low), medium).
result(xray(one_quad), gipox(mid), compliance(mid), pressure(mid), medium).
result(xray(one_quad), gipox(mid), compliance(mid), pressure(high), medium).
result(xray(one_quad), gipox(mid), compliance(mid), pressure(very_high), medium).
result(xray(one_quad), gipox(mid), compliance(low), pressure(very_low), medium).
result(xray(one_quad), gipox(mid), compliance(low), pressure(low), medium).
result(xray(one_quad), gipox(mid), compliance(low), pressure(mid), medium).
result(xray(one_quad), gipox(mid), compliance(low), pressure(high), medium).
result(xray(one_quad), gipox(mid), compliance(low), pressure(very_high), severe).
result(xray(one_quad), gipox(mid), compliance(very_low), pressure(very_low), medium).
result(xray(one_quad), gipox(mid), compliance(very_low), pressure(low), medium).
result(xray(one_quad), gipox(mid), compliance(very_low), pressure(mid), medium).
result(xray(one_quad), gipox(mid), compliance(very_low), pressure(high), severe).
result(xray(one_quad), gipox(mid), compliance(very_low), pressure(very_high), severe).
result(xray(one_quad), gipox(low), compliance(very_high), pressure(very_low), medium).
result(xray(one_quad), gipox(low), compliance(very_high), pressure(low), medium).
result(xray(one_quad), gipox(low), compliance(very_high), pressure(mid), medium).
result(xray(one_quad), gipox(low), compliance(very_high), pressure(high), medium).
result(xray(one_quad), gipox(low), compliance(very_high), pressure(very_high), medium).
result(xray(one_quad), gipox(low), compliance(high), pressure(very_low), medium).
result(xray(one_quad), gipox(low), compliance(high), pressure(low), medium).
result(xray(one_quad), gipox(low), compliance(high), pressure(mid), medium).
result(xray(one_quad), gipox(low), compliance(high), pressure(high), medium).
result(xray(one_quad), gipox(low), compliance(high), pressure(very_high), medium).
result(xray(one_quad), gipox(low), compliance(mid), pressure(very_low), medium).
result(xray(one_quad), gipox(low), compliance(mid), pressure(low), medium).
result(xray(one_quad), gipox(low), compliance(mid), pressure(mid), medium).
result(xray(one_quad), gipox(low), compliance(mid), pressure(high), medium).
result(xray(one_quad), gipox(low), compliance(mid), pressure(very_high), severe).
result(xray(one_quad), gipox(low), compliance(low), pressure(very_low), medium).
result(xray(one_quad), gipox(low), compliance(low), pressure(low), medium).
result(xray(one_quad), gipox(low), compliance(low), pressure(mid), medium).
result(xray(one_quad), gipox(low), compliance(low), pressure(high), severe).
result(xray(one_quad), gipox(low), compliance(low), pressure(very_high), severe).
result(xray(one_quad), gipox(low), compliance(very_low), pressure(very_low), medium).
result(xray(one_quad), gipox(low), compliance(very_low), pressure(low), medium).
result(xray(one_quad), gipox(low), compliance(very_low), pressure(mid), severe).
result(xray(one_quad), gipox(low), compliance(very_low), pressure(high), severe).
result(xray(one_quad), gipox(low), compliance(very_low), pressure(very_high), severe).
result(xray(one_quad), gipox(very_low), compliance(very_high), pressure(very_low), medium).
result(xray(one_quad), gipox(very_low), compliance(very_high), pressure(low), medium).
result(xray(one_quad), gipox(very_low), compliance(very_high), pressure(mid), medium).
result(xray(one_quad), gipox(very_low), compliance(very_high), pressure(high), medium).
result(xray(one_quad), gipox(very_low), compliance(very_high), pressure(very_high), medium).
result(xray(one_quad), gipox(very_low), compliance(high), pressure(very_low), medium).
result(xray(one_quad), gipox(very_low), compliance(high), pressure(low), medium).
result(xray(one_quad), gipox(very_low), compliance(high), pressure(mid), medium).
result(xray(one_quad), gipox(very_low), compliance(high), pressure(high), medium).
result(xray(one_quad), gipox(very_low), compliance(high), pressure(very_high), severe).
result(xray(one_quad), gipox(very_low), compliance(mid), pressure(very_low), medium).
result(xray(one_quad), gipox(very_low), compliance(mid), pressure(low), medium).
result(xray(one_quad), gipox(very_low), compliance(mid), pressure(mid), medium).
result(xray(one_quad), gipox(very_low), compliance(mid), pressure(high), severe).
result(xray(one_quad), gipox(very_low), compliance(mid), pressure(very_high), severe).
result(xray(one_quad), gipox(very_low), compliance(low), pressure(very_low), medium).
result(xray(one_quad), gipox(very_low), compliance(low), pressure(low), medium).
result(xray(one_quad), gipox(very_low), compliance(low), pressure(mid), severe).
result(xray(one_quad), gipox(very_low), compliance(low), pressure(high), severe).
result(xray(one_quad), gipox(very_low), compliance(low), pressure(very_high), severe).
result(xray(one_quad), gipox(very_low), compliance(very_low), pressure(very_low), medium).
result(xray(one_quad), gipox(very_low), compliance(very_low), pressure(low), severe).
result(xray(one_quad), gipox(very_low), compliance(very_low), pressure(mid), severe).
result(xray(one_quad), gipox(very_low), compliance(very_low), pressure(high), severe).
result(xray(one_quad), gipox(very_low), compliance(very_low), pressure(very_high), severe).
result(xray(two_quad), gipox(very_high), compliance(very_high), pressure(very_low), small).
result(xray(two_quad), gipox(very_high), compliance(very_high), pressure(low), small).
result(xray(two_quad), gipox(very_high), compliance(very_high), pressure(mid), medium).
result(xray(two_quad), gipox(very_high), compliance(very_high), pressure(high), medium).
result(xray(two_quad), gipox(very_high), compliance(very_high), pressure(very_high), medium).
result(xray(two_quad), gipox(very_high), compliance(high), pressure(very_low), small).
result(xray(two_quad), gipox(very_high), compliance(high), pressure(low), medium).
result(xray(two_quad), gipox(very_high), compliance(high), pressure(mid), medium).
result(xray(two_quad), gipox(very_high), compliance(high), pressure(high), medium).
result(xray(two_quad), gipox(very_high), compliance(high), pressure(very_high), medium).
result(xray(two_quad), gipox(very_high), compliance(mid), pressure(very_low), medium).
result(xray(two_quad), gipox(very_high), compliance(mid), pressure(low), medium).
result(xray(two_quad), gipox(very_high), compliance(mid), pressure(mid), medium).
result(xray(two_quad), gipox(very_high), compliance(mid), pressure(high), medium).
result(xray(two_quad), gipox(very_high), compliance(mid), pressure(very_high), medium).
result(xray(two_quad), gipox(very_high), compliance(low), pressure(very_low), medium).
result(xray(two_quad), gipox(very_high), compliance(low), pressure(low), medium).
result(xray(two_quad), gipox(very_high), compliance(low), pressure(mid), medium).
result(xray(two_quad), gipox(very_high), compliance(low), pressure(high), medium).
result(xray(two_quad), gipox(very_high), compliance(low), pressure(very_high), medium).
result(xray(two_quad), gipox(very_high), compliance(very_low), pressure(very_low), medium).
result(xray(two_quad), gipox(very_high), compliance(very_low), pressure(low), medium).
result(xray(two_quad), gipox(very_high), compliance(very_low), pressure(mid), medium).
result(xray(two_quad), gipox(very_high), compliance(very_low), pressure(high), medium).
result(xray(two_quad), gipox(very_high), compliance(very_low), pressure(very_high), severe).
result(xray(two_quad), gipox(high), compliance(very_high), pressure(very_low), small).
result(xray(two_quad), gipox(high), compliance(very_high), pressure(low), medium).
result(xray(two_quad), gipox(high), compliance(very_high), pressure(mid), medium).
result(xray(two_quad), gipox(high), compliance(very_high), pressure(high), medium).
result(xray(two_quad), gipox(high), compliance(very_high), pressure(very_high), medium).
result(xray(two_quad), gipox(high), compliance(high), pressure(very_low), medium).
result(xray(two_quad), gipox(high), compliance(high), pressure(low), medium).
result(xray(two_quad), gipox(high), compliance(high), pressure(mid), medium).
result(xray(two_quad), gipox(high), compliance(high), pressure(high), medium).
result(xray(two_quad), gipox(high), compliance(high), pressure(very_high), medium).
result(xray(two_quad), gipox(high), compliance(mid), pressure(very_low), medium).
result(xray(two_quad), gipox(high), compliance(mid), pressure(low), medium).
result(xray(two_quad), gipox(high), compliance(mid), pressure(mid), medium).
result(xray(two_quad), gipox(high), compliance(mid), pressure(high), medium).
result(xray(two_quad), gipox(high), compliance(mid), pressure(very_high), medium).
result(xray(two_quad), gipox(high), compliance(low), pressure(very_low), medium).
result(xray(two_quad), gipox(high), compliance(low), pressure(low), medium).
result(xray(two_quad), gipox(high), compliance(low), pressure(mid), medium).
result(xray(two_quad), gipox(high), compliance(low), pressure(high), medium).
result(xray(two_quad), gipox(high), compliance(low), pressure(very_high), severe).
result(xray(two_quad), gipox(high), compliance(very_low), pressure(very_low), medium).
result(xray(two_quad), gipox(high), compliance(very_low), pressure(low), medium).
result(xray(two_quad), gipox(high), compliance(very_low), pressure(mid), medium).
result(xray(two_quad), gipox(high), compliance(very_low), pressure(high), severe).
result(xray(two_quad), gipox(high), compliance(very_low), pressure(very_high), severe).
result(xray(two_quad), gipox(mid), compliance(very_high), pressure(very_low), medium).
result(xray(two_quad), gipox(mid), compliance(very_high), pressure(low), medium).
result(xray(two_quad), gipox(mid), compliance(very_high), pressure(mid), medium).
result(xray(two_quad), gipox(mid), compliance(very_high), pressure(high), medium).
result(xray(two_quad), gipox(mid), compliance(very_high), pressure(very_high), medium).
result(xray(two_quad), gipox(mid), compliance(high), pressure(very_low), medium).
result(xray(two_quad), gipox(mid), compliance(high), pressure(low), medium).
result(xray(two_quad), gipox(mid), compliance(high), pressure(mid), medium).
result(xray(two_quad), gipox(mid), compliance(high), pressure(high), medium).
result(xray(two_quad), gipox(mid), compliance(high), pressure(very_high), medium).
result(xray(two_quad), gipox(mid), compliance(mid), pressure(very_low), medium).
result(xray(two_quad), gipox(mid), compliance(mid), pressure(low), medium).
result(xray(two_quad), gipox(mid), compliance(mid), pressure(mid), medium).
result(xray(two_quad), gipox(mid), compliance(mid), pressure(high), medium).
result(xray(two_quad), gipox(mid), compliance(mid), pressure(very_high), severe).
result(xray(two_quad), gipox(mid), compliance(low), pressure(very_low), medium).
result(xray(two_quad), gipox(mid), compliance(low), pressure(low), medium).
result(xray(two_quad), gipox(mid), compliance(low), pressure(mid), medium).
result(xray(two_quad), gipox(mid), compliance(low), pressure(high), severe).
result(xray(two_quad), gipox(mid), compliance(low), pressure(very_high), severe).
result(xray(two_quad), gipox(mid), compliance(very_low), pressure(very_low), medium).
result(xray(two_quad), gipox(mid), compliance(very_low), pressure(low), medium).
result(xray(two_quad), gipox(mid), compliance(very_low), pressure(mid), severe).
result(xray(two_quad), gipox(mid), compliance(very_low), pressure(high), severe).
result(xray(two_quad), gipox(mid), compliance(very_low), pressure(very_high), severe).
result(xray(two_quad), gipox(low), compliance(very_high), pressure(very_low), medium).
result(xray(two_quad), gipox(low), compliance(very_high), pressure(low), medium).
result(xray(two_quad), gipox(low), compliance(very_high), pressure(mid), medium).
result(xray(two_quad), gipox(low), compliance(very_high), pressure(high), medium).
result(xray(two_quad), gipox(low), compliance(very_high), pressure(very_high), medium).
result(xray(two_quad), gipox(low), compliance(high), pressure(very_low), medium).
result(xray(two_quad), gipox(low), compliance(high), pressure(low), medium).
result(xray(two_quad), gipox(low), compliance(high), pressure(mid), medium).
result(xray(two_quad), gipox(low), compliance(high), pressure(high), medium).
result(xray(two_quad), gipox(low), compliance(high), pressure(very_high), severe).
result(xray(two_quad), gipox(low), compliance(mid), pressure(very_low), medium).
result(xray(two_quad), gipox(low), compliance(mid), pressure(low), medium).
result(xray(two_quad), gipox(low), compliance(mid), pressure(mid), medium).
result(xray(two_quad), gipox(low), compliance(mid), pressure(high), severe).
result(xray(two_quad), gipox(low), compliance(mid), pressure(very_high), severe).
result(xray(two_quad), gipox(low), compliance(low), pressure(very_low), medium).
result(xray(two_quad), gipox(low), compliance(low), pressure(low), medium).
result(xray(two_quad), gipox(low), compliance(low), pressure(mid), severe).
result(xray(two_quad), gipox(low), compliance(low), pressure(high), severe).
result(xray(two_quad), gipox(low), compliance(low), pressure(very_high), severe).
result(xray(two_quad), gipox(low), compliance(very_low), pressure(very_low), medium).
result(xray(two_quad), gipox(low), compliance(very_low), pressure(low), severe).
result(xray(two_quad), gipox(low), compliance(very_low), pressure(mid), severe).
result(xray(two_quad), gipox(low), compliance(very_low), pressure(high), severe).
result(xray(two_quad), gipox(low), compliance(very_low), pressure(very_high), severe).
result(xray(two_quad), gipox(very_low), compliance(very_high), pressure(very_low), medium).
result(xray(two_quad), gipox(very_low), compliance(very_high), pressure(low), medium).
result(xray(two_quad), gipox(very_low), compliance(very_high), pressure(mid), medium).
result(xray(two_quad), gipox(very_low), compliance(very_high), pressure(high), medium).
result(xray(two_quad), gipox(very_low), compliance(very_high), pressure(very_high), severe).
result(xray(two_quad), gipox(very_low), compliance(high), pressure(very_low), medium).
result(xray(two_quad), gipox(very_low), compliance(high), pressure(low), medium).
result(xray(two_quad), gipox(very_low), compliance(high), pressure(mid), medium).
result(xray(two_quad), gipox(very_low), compliance(high), pressure(high), severe).
result(xray(two_quad), gipox(very_low), compliance(high), pressure(very_high), severe).
result(xray(two_quad), gipox(very_low), compliance(mid), pressure(very_low), medium).
result(xray(two_quad), gipox(very_low), compliance(mid), pressure(low), medium).
result(xray(two_quad), gipox(very_low), compliance(mid), pressure(mid), severe).
result(xray(two_quad), gipox(very_low), compliance(mid), pressure(high), severe).
result(xray(two_quad), gipox(very_low), compliance(mid), pressure(very_high), severe).
result(xray(two_quad), gipox(very_low), compliance(low), pressure(very_low), medium).
result(xray(two_quad), gipox(very_low), compliance(low), pressure(low), severe).
result(xray(two_quad), gipox(very_low), compliance(low), pressure(mid), severe).
result(xray(two_quad), gipox(very_low), compliance(low), pressure(high), severe).
result(xray(two_quad), gipox(very_low), compliance(low), pressure(very_high), severe).
result(xray(two_quad), gipox(very_low), compliance(very_low), pressure(very_low), severe).
result(xray(two_quad), gipox(very_low), compliance(very_low), pressure(low), severe).
result(xray(two_quad), gipox(very_low), compliance(very_low), pressure(mid), severe).
result(xray(two_quad), gipox(very_low), compliance(very_low), pressure(high), severe).
result(xray(two_quad), gipox(very_low), compliance(very_low), pressure(very_high), severe).
result(xray(three_quad), gipox(very_high), compliance(very_high), pressure(very_low), small).
result(xray(three_quad), gipox(very_high), compliance(very_high), pressure(low), medium).
result(xray(three_quad), gipox(very_high), compliance(very_high), pressure(mid), medium).
result(xray(three_quad), gipox(very_high), compliance(very_high), pressure(high), medium).
result(xray(three_quad), gipox(very_high), compliance(very_high), pressure(very_high), medium).
result(xray(three_quad), gipox(very_high), compliance(high), pressure(very_low), medium).
result(xray(three_quad), gipox(very_high), compliance(high), pressure(low), medium).
result(xray(three_quad), gipox(very_high), compliance(high), pressure(mid), medium).
result(xray(three_quad), gipox(very_high), compliance(high), pressure(high), medium).
result(xray(three_quad), gipox(very_high), compliance(high), pressure(very_high), medium).
result(xray(three_quad), gipox(very_high), compliance(mid), pressure(very_low), medium).
result(xray(three_quad), gipox(very_high), compliance(mid), pressure(low), medium).
result(xray(three_quad), gipox(very_high), compliance(mid), pressure(mid), medium).
result(xray(three_quad), gipox(very_high), compliance(mid), pressure(high), medium).
result(xray(three_quad), gipox(very_high), compliance(mid), pressure(very_high), medium).
result(xray(three_quad), gipox(very_high), compliance(low), pressure(very_low), medium).
result(xray(three_quad), gipox(very_high), compliance(low), pressure(low), medium).
result(xray(three_quad), gipox(very_high), compliance(low), pressure(mid), medium).
result(xray(three_quad), gipox(very_high), compliance(low), pressure(high), medium).
result(xray(three_quad), gipox(very_high), compliance(low), pressure(very_high), severe).
result(xray(three_quad), gipox(very_high), compliance(very_low), pressure(very_low), medium).
result(xray(three_quad), gipox(very_high), compliance(very_low), pressure(low), medium).
result(xray(three_quad), gipox(very_high), compliance(very_low), pressure(mid), medium).
result(xray(three_quad), gipox(very_high), compliance(very_low), pressure(high), severe).
result(xray(three_quad), gipox(very_high), compliance(very_low), pressure(very_high), severe).
result(xray(three_quad), gipox(high), compliance(very_high), pressure(very_low), medium).
result(xray(three_quad), gipox(high), compliance(very_high), pressure(low), medium).
result(xray(three_quad), gipox(high), compliance(very_high), pressure(mid), medium).
result(xray(three_quad), gipox(high), compliance(very_high), pressure(high), medium).
result(xray(three_quad), gipox(high), compliance(very_high), pressure(very_high), medium).
result(xray(three_quad), gipox(high), compliance(high), pressure(very_low), medium).
result(xray(three_quad), gipox(high), compliance(high), pressure(low), medium).
result(xray(three_quad), gipox(high), compliance(high), pressure(mid), medium).
result(xray(three_quad), gipox(high), compliance(high), pressure(high), medium).
result(xray(three_quad), gipox(high), compliance(high), pressure(very_high), medium).
result(xray(three_quad), gipox(high), compliance(mid), pressure(very_low), medium).
result(xray(three_quad), gipox(high), compliance(mid), pressure(low), medium).
result(xray(three_quad), gipox(high), compliance(mid), pressure(mid), medium).
result(xray(three_quad), gipox(high), compliance(mid), pressure(high), medium).
result(xray(three_quad), gipox(high), compliance(mid), pressure(very_high), severe).
result(xray(three_quad), gipox(high), compliance(low), pressure(very_low), medium).
result(xray(three_quad), gipox(high), compliance(low), pressure(low), medium).
result(xray(three_quad), gipox(high), compliance(low), pressure(mid), medium).
result(xray(three_quad), gipox(high), compliance(low), pressure(high), severe).
result(xray(three_quad), gipox(high), compliance(low), pressure(very_high), severe).
result(xray(three_quad), gipox(high), compliance(very_low), pressure(very_low), medium).
result(xray(three_quad), gipox(high), compliance(very_low), pressure(low), medium).
result(xray(three_quad), gipox(high), compliance(very_low), pressure(mid), severe).
result(xray(three_quad), gipox(high), compliance(very_low), pressure(high), severe).
result(xray(three_quad), gipox(high), compliance(very_low), pressure(very_high), severe).
result(xray(three_quad), gipox(mid), compliance(very_high), pressure(very_low), medium).
result(xray(three_quad), gipox(mid), compliance(very_high), pressure(low), medium).
result(xray(three_quad), gipox(mid), compliance(very_high), pressure(mid), medium).
result(xray(three_quad), gipox(mid), compliance(very_high), pressure(high), medium).
result(xray(three_quad), gipox(mid), compliance(very_high), pressure(very_high), medium).
result(xray(three_quad), gipox(mid), compliance(high), pressure(very_low), medium).
result(xray(three_quad), gipox(mid), compliance(high), pressure(low), medium).
result(xray(three_quad), gipox(mid), compliance(high), pressure(mid), medium).
result(xray(three_quad), gipox(mid), compliance(high), pressure(high), medium).
result(xray(three_quad), gipox(mid), compliance(high), pressure(very_high), severe).
result(xray(three_quad), gipox(mid), compliance(mid), pressure(very_low), medium).
result(xray(three_quad), gipox(mid), compliance(mid), pressure(low), medium).
result(xray(three_quad), gipox(mid), compliance(mid), pressure(mid), medium).
result(xray(three_quad), gipox(mid), compliance(mid), pressure(high), severe).
result(xray(three_quad), gipox(mid), compliance(mid), pressure(very_high), severe).
result(xray(three_quad), gipox(mid), compliance(low), pressure(very_low), medium).
result(xray(three_quad), gipox(mid), compliance(low), pressure(low), medium).
result(xray(three_quad), gipox(mid), compliance(low), pressure(mid), severe).
result(xray(three_quad), gipox(mid), compliance(low), pressure(high), severe).
result(xray(three_quad), gipox(mid), compliance(low), pressure(very_high), severe).
result(xray(three_quad), gipox(mid), compliance(very_low), pressure(very_low), medium).
result(xray(three_quad), gipox(mid), compliance(very_low), pressure(low), severe).
result(xray(three_quad), gipox(mid), compliance(very_low), pressure(mid), severe).
result(xray(three_quad), gipox(mid), compliance(very_low), pressure(high), severe).
result(xray(three_quad), gipox(mid), compliance(very_low), pressure(very_high), severe).
result(xray(three_quad), gipox(low), compliance(very_high), pressure(very_low), medium).
result(xray(three_quad), gipox(low), compliance(very_high), pressure(low), medium).
result(xray(three_quad), gipox(low), compliance(very_high), pressure(mid), medium).
result(xray(three_quad), gipox(low), compliance(very_high), pressure(high), medium).
result(xray(three_quad), gipox(low), compliance(very_high), pressure(very_high), severe).
result(xray(three_quad), gipox(low), compliance(high), pressure(very_low), medium).
result(xray(three_quad), gipox(low), compliance(high), pressure(low), medium).
result(xray(three_quad), gipox(low), compliance(high), pressure(mid), medium).
result(xray(three_quad), gipox(low), compliance(high), pressure(high), severe).
result(xray(three_quad), gipox(low), compliance(high), pressure(very_high), severe).
result(xray(three_quad), gipox(low), compliance(mid), pressure(very_low), medium).
result(xray(three_quad), gipox(low), compliance(mid), pressure(low), medium).
result(xray(three_quad), gipox(low), compliance(mid), pressure(mid), severe).
result(xray(three_quad), gipox(low), compliance(mid), pressure(high), severe).
result(xray(three_quad), gipox(low), compliance(mid), pressure(very_high), severe).
result(xray(three_quad), gipox(low), compliance(low), pressure(very_low), medium).
result(xray(three_quad), gipox(low), compliance(low), pressure(low), severe).
result(xray(three_quad), gipox(low), compliance(low), pressure(mid), severe).
result(xray(three_quad), gipox(low), compliance(low), pressure(high), severe).
result(xray(three_quad), gipox(low), compliance(low), pressure(very_high), severe).
result(xray(three_quad), gipox(low), compliance(very_low), pressure(very_low), severe).
result(xray(three_quad), gipox(low), compliance(very_low), pressure(low), severe).
result(xray(three_quad), gipox(low), compliance(very_low), pressure(mid), severe).
result(xray(three_quad), gipox(low), compliance(very_low), pressure(high), severe).
result(xray(three_quad), gipox(low), compliance(very_low), pressure(very_high), severe).
result(xray(three_quad), gipox(very_low), compliance(very_high), pressure(very_low), medium).
result(xray(three_quad), gipox(very_low), compliance(very_high), pressure(low), medium).
result(xray(three_quad), gipox(very_low), compliance(very_high), pressure(mid), medium).
result(xray(three_quad), gipox(very_low), compliance(very_high), pressure(high), severe).
result(xray(three_quad), gipox(very_low), compliance(very_high), pressure(very_high), severe).
result(xray(three_quad), gipox(very_low), compliance(high), pressure(very_low), medium).
result(xray(three_quad), gipox(very_low), compliance(high), pressure(low), medium).
result(xray(three_quad), gipox(very_low), compliance(high), pressure(mid), severe).
result(xray(three_quad), gipox(very_low), compliance(high), pressure(high), severe).
result(xray(three_quad), gipox(very_low), compliance(high), pressure(very_high), severe).
result(xray(three_quad), gipox(very_low), compliance(mid), pressure(very_low), medium).
result(xray(three_quad), gipox(very_low), compliance(mid), pressure(low), severe).
result(xray(three_quad), gipox(very_low), compliance(mid), pressure(mid), severe).
result(xray(three_quad), gipox(very_low), compliance(mid), pressure(high), severe).
result(xray(three_quad), gipox(very_low), compliance(mid), pressure(very_high), severe).
result(xray(three_quad), gipox(very_low), compliance(low), pressure(very_low), severe).
result(xray(three_quad), gipox(very_low), compliance(low), pressure(low), severe).
result(xray(three_quad), gipox(very_low), compliance(low), pressure(mid), severe).
result(xray(three_quad), gipox(very_low), compliance(low), pressure(high), severe).
result(xray(three_quad), gipox(very_low), compliance(low), pressure(very_high), severe).
result(xray(three_quad), gipox(very_low), compliance(very_low), pressure(very_low), severe).
result(xray(three_quad), gipox(very_low), compliance(very_low), pressure(low), severe).
result(xray(three_quad), gipox(very_low), compliance(very_low), pressure(mid), severe).
result(xray(three_quad), gipox(very_low), compliance(very_low), pressure(high), severe).
result(xray(three_quad), gipox(very_low), compliance(very_low), pressure(very_high), severe).
result(xray(four_quad), gipox(very_high), compliance(very_high), pressure(very_low), medium).
result(xray(four_quad), gipox(very_high), compliance(very_high), pressure(low), medium).
result(xray(four_quad), gipox(very_high), compliance(very_high), pressure(mid), medium).
result(xray(four_quad), gipox(very_high), compliance(very_high), pressure(high), medium).
result(xray(four_quad), gipox(very_high), compliance(very_high), pressure(very_high), medium).
result(xray(four_quad), gipox(very_high), compliance(high), pressure(very_low), medium).
result(xray(four_quad), gipox(very_high), compliance(high), pressure(low), medium).
result(xray(four_quad), gipox(very_high), compliance(high), pressure(mid), medium).
result(xray(four_quad), gipox(very_high), compliance(high), pressure(high), medium).
result(xray(four_quad), gipox(very_high), compliance(high), pressure(very_high), medium).
result(xray(four_quad), gipox(very_high), compliance(mid), pressure(very_low), medium).
result(xray(four_quad), gipox(very_high), compliance(mid), pressure(low), medium).
result(xray(four_quad), gipox(very_high), compliance(mid), pressure(mid), medium).
result(xray(four_quad), gipox(very_high), compliance(mid), pressure(high), medium).
result(xray(four_quad), gipox(very_high), compliance(mid), pressure(very_high), severe).
result(xray(four_quad), gipox(very_high), compliance(low), pressure(very_low), medium).
result(xray(four_quad), gipox(very_high), compliance(low), pressure(low), medium).
result(xray(four_quad), gipox(very_high), compliance(low), pressure(mid), medium).
result(xray(four_quad), gipox(very_high), compliance(low), pressure(high), severe).
result(xray(four_quad), gipox(very_high), compliance(low), pressure(very_high), severe).
result(xray(four_quad), gipox(very_high), compliance(very_low), pressure(very_low), medium).
result(xray(four_quad), gipox(very_high), compliance(very_low), pressure(low), medium).
result(xray(four_quad), gipox(very_high), compliance(very_low), pressure(mid), severe).
result(xray(four_quad), gipox(very_high), compliance(very_low), pressure(high), severe).
result(xray(four_quad), gipox(very_high), compliance(very_low), pressure(very_high), severe).
result(xray(four_quad), gipox(high), compliance(very_high), pressure(very_low), medium).
result(xray(four_quad), gipox(high), compliance(very_high), pressure(low), medium).
result(xray(four_quad), gipox(high), compliance(very_high), pressure(mid), medium).
result(xray(four_quad), gipox(high), compliance(very_high), pressure(high), medium).
result(xray(four_quad), gipox(high), compliance(very_high), pressure(very_high), medium).
result(xray(four_quad), gipox(high), compliance(high), pressure(very_low), medium).
result(xray(four_quad), gipox(high), compliance(high), pressure(low), medium).
result(xray(four_quad), gipox(high), compliance(high), pressure(mid), medium).
result(xray(four_quad), gipox(high), compliance(high), pressure(high), medium).
result(xray(four_quad), gipox(high), compliance(high), pressure(very_high), severe).
result(xray(four_quad), gipox(high), compliance(mid), pressure(very_low), medium).
result(xray(four_quad), gipox(high), compliance(mid), pressure(low), medium).
result(xray(four_quad), gipox(high), compliance(mid), pressure(mid), medium).
result(xray(four_quad), gipox(high), compliance(mid), pressure(high), severe).
result(xray(four_quad), gipox(high), compliance(mid), pressure(very_high), severe).
result(xray(four_quad), gipox(high), compliance(low), pressure(very_low), medium).
result(xray(four_quad), gipox(high), compliance(low), pressure(low), medium).
result(xray(four_quad), gipox(high), compliance(low), pressure(mid), severe).
result(xray(four_quad), gipox(high), compliance(low), pressure(high), severe).
result(xray(four_quad), gipox(high), compliance(low), pressure(very_high), severe).
result(xray(four_quad), gipox(high), compliance(very_low), pressure(very_low), medium).
result(xray(four_quad), gipox(high), compliance(very_low), pressure(low), severe).
result(xray(four_quad), gipox(high), compliance(very_low), pressure(mid), severe).
result(xray(four_quad), gipox(high), compliance(very_low), pressure(high), severe).
result(xray(four_quad), gipox(high), compliance(very_low), pressure(very_high), severe).
result(xray(four_quad), gipox(mid), compliance(very_high), pressure(very_low), medium).
result(xray(four_quad), gipox(mid), compliance(very_high), pressure(low), medium).
result(xray(four_quad), gipox(mid), compliance(very_high), pressure(mid), medium).
result(xray(four_quad), gipox(mid), compliance(very_high), pressure(high), medium).
result(xray(four_quad), gipox(mid), compliance(very_high), pressure(very_high), severe).
result(xray(four_quad), gipox(mid), compliance(high), pressure(very_low), medium).
result(xray(four_quad), gipox(mid), compliance(high), pressure(low), medium).
result(xray(four_quad), gipox(mid), compliance(high), pressure(mid), medium).
result(xray(four_quad), gipox(mid), compliance(high), pressure(high), severe).
result(xray(four_quad), gipox(mid), compliance(high), pressure(very_high), severe).
result(xray(four_quad), gipox(mid), compliance(mid), pressure(very_low), medium).
result(xray(four_quad), gipox(mid), compliance(mid), pressure(low), medium).
result(xray(four_quad), gipox(mid), compliance(mid), pressure(mid), severe).
result(xray(four_quad), gipox(mid), compliance(mid), pressure(high), severe).
result(xray(four_quad), gipox(mid), compliance(mid), pressure(very_high), severe).
result(xray(four_quad), gipox(mid), compliance(low), pressure(very_low), medium).
result(xray(four_quad), gipox(mid), compliance(low), pressure(low), severe).
result(xray(four_quad), gipox(mid), compliance(low), pressure(mid), severe).
result(xray(four_quad), gipox(mid), compliance(low), pressure(high), severe).
result(xray(four_quad), gipox(mid), compliance(low), pressure(very_high), severe).
result(xray(four_quad), gipox(mid), compliance(very_low), pressure(very_low), severe).
result(xray(four_quad), gipox(mid), compliance(very_low), pressure(low), severe).
result(xray(four_quad), gipox(mid), compliance(very_low), pressure(mid), severe).
result(xray(four_quad), gipox(mid), compliance(very_low), pressure(high), severe).
result(xray(four_quad), gipox(mid), compliance(very_low), pressure(very_high), severe).
result(xray(four_quad), gipox(low), compliance(very_high), pressure(very_low), medium).
result(xray(four_quad), gipox(low), compliance(very_high), pressure(low), medium).
result(xray(four_quad), gipox(low), compliance(very_high), pressure(mid), medium).
result(xray(four_quad), gipox(low), compliance(very_high), pressure(high), severe).
result(xray(four_quad), gipox(low), compliance(very_high), pressure(very_high), severe).
result(xray(four_quad), gipox(low), compliance(high), pressure(very_low), medium).
result(xray(four_quad), gipox(low), compliance(high), pressure(low), medium).
result(xray(four_quad), gipox(low), compliance(high), pressure(mid), severe).
result(xray(four_quad), gipox(low), compliance(high), pressure(high), severe).
result(xray(four_quad), gipox(low), compliance(high), pressure(very_high), severe).
result(xray(four_quad), gipox(low), compliance(mid), pressure(very_low), medium).
result(xray(four_quad), gipox(low), compliance(mid), pressure(low), severe).
result(xray(four_quad), gipox(low), compliance(mid), pressure(mid), severe).
result(xray(four_quad), gipox(low), compliance(mid), pressure(high), severe).
result(xray(four_quad), gipox(low), compliance(mid), pressure(very_high), severe).
result(xray(four_quad), gipox(low), compliance(low), pressure(very_low), severe).
result(xray(four_quad), gipox(low), compliance(low), pressure(low), severe).
result(xray(four_quad), gipox(low), compliance(low), pressure(mid), severe).
result(xray(four_quad), gipox(low), compliance(low), pressure(high), severe).
result(xray(four_quad), gipox(low), compliance(low), pressure(very_high), severe).
result(xray(four_quad), gipox(low), compliance(very_low), pressure(very_low), severe).
result(xray(four_quad), gipox(low), compliance(very_low), pressure(low), severe).
result(xray(four_quad), gipox(low), compliance(very_low), pressure(mid), severe).
result(xray(four_quad), gipox(low), compliance(very_low), pressure(high), severe).
result(xray(four_quad), gipox(low), compliance(very_low), pressure(very_high), severe).
result(xray(four_quad), gipox(very_low), compliance(very_high), pressure(very_low), medium).
result(xray(four_quad), gipox(very_low), compliance(very_high), pressure(low), medium).
result(xray(four_quad), gipox(very_low), compliance(very_high), pressure(mid), severe).
result(xray(four_quad), gipox(very_low), compliance(very_high), pressure(high), severe).
result(xray(four_quad), gipox(very_low), compliance(very_high), pressure(very_high), severe).
result(xray(four_quad), gipox(very_low), compliance(high), pressure(very_low), medium).
result(xray(four_quad), gipox(very_low), compliance(high), pressure(low), severe).
result(xray(four_quad), gipox(very_low), compliance(high), pressure(mid), severe).
result(xray(four_quad), gipox(very_low), compliance(high), pressure(high), severe).
result(xray(four_quad), gipox(very_low), compliance(high), pressure(very_high), severe).
result(xray(four_quad), gipox(very_low), compliance(mid), pressure(very_low), severe).
result(xray(four_quad), gipox(very_low), compliance(mid), pressure(low), severe).
result(xray(four_quad), gipox(very_low), compliance(mid), pressure(mid), severe).
result(xray(four_quad), gipox(very_low), compliance(mid), pressure(high), severe).
result(xray(four_quad), gipox(very_low), compliance(mid), pressure(very_high), severe).
result(xray(four_quad), gipox(very_low), compliance(low), pressure(very_low), severe).
result(xray(four_quad), gipox(very_low), compliance(low), pressure(low), severe).
result(xray(four_quad), gipox(very_low), compliance(low), pressure(mid), severe).
result(xray(four_quad), gipox(very_low), compliance(low), pressure(high), severe).
result(xray(four_quad), gipox(very_low), compliance(low), pressure(very_high), severe).
result(xray(four_quad), gipox(very_low), compliance(very_low), pressure(very_low), severe).
result(xray(four_quad), gipox(very_low), compliance(very_low), pressure(low), severe).
result(xray(four_quad), gipox(very_low), compliance(very_low), pressure(mid), severe).
result(xray(four_quad), gipox(very_low), compliance(very_low), pressure(high), severe).
result(xray(four_quad), gipox(very_low), compliance(very_low), pressure(very_high), severe).
